services:
  backend:
    container_name: aurora-backend
    build:
      context: ./aurora-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./aurora-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=mongodb://root:password123@db:27017/mydatabase?authSource=admin
    depends_on:
      - db

  frontend:
    container_name: aurora-frontend
    build:
      context: ./aurora-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./aurora-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend

  db:
    container_name: aurora-bd
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}